### ISSUE TITLE
non ascii characters in excel

### ISSUE THREAD

**Issue by evrens** [sense-of-security/ADRecon#1]
Hi,
non-ascii characters are not displayed correctly in excel report.

![image](https://user-images.githubusercontent.com/28725719/34555437-d81b937e-f142-11e7-8231-a4d3e8dccc1e.png)

**Comment by prashant3535** [comment]
Hi,

Could you please confirm if the issue is resolved by adding the following line: (Add to Line 1664)

`$worksheet.QueryTables.item($Connector.name).TextFilePlatform = 65001`
