### ISSUE TITLE
Total user accounts

### ISSUE THREAD

**Issue by apperrault** [sense-of-security/ADRecon#10]
First, great software.  It has been a lifesaver for me and my company.  The 3 times I have run it, when I go to the User Stats, the code says ` =CountA(Users!A301:A301)-1`.  and I always end up with a total of 0 in Red, and the percentages are always throwing a divide by zero error.  is that correct?

thanks

**Comment by prashant3535** [comment]
HI,

Could you please provide additional information about how ADRecon was executed (using RSAT/LDAP) and the version of MS Office?  Are there any blank fields in the Enabled column in the users sheet?

In the [sample output](https://github.com/sense-of-security/ADRecon/blob/master/Sample%20Output/ADRecon-Report-20180828223537/sos.labs-ADRecon-Report.xlsx), the formula calculated is `=COUNTA(Users!A:A)-1` by the following line:
[https://github.com/sense-of-security/ADRecon/blob/master/ADRecon.ps1#L3215](https://github.com/sense-of-security/ADRecon/blob/master/ADRecon.ps1#L3215)

**Comment by apperrault** [comment]
I am running this using RSAT simply running adrecon.ps1.  I am running with from a Windows 10 system, with the RSAT tools installed, using Domain Admin rights.  I don't see any empty columns in my users csv or in the excel document

**Comment by apperrault** [comment]
Also, if i change the formula to `=COUNTA(Users!A:A) -1` it works just fine

**Comment by prashant3535** [comment]
Hi, 

Could you please confirm if [this](https://github.com/sense-of-security/ADRecon/commit/1c5f10828f275c48dde3902ef387939af7c66dec) commit resolves the issue for you ?

**Comment by apperrault** [comment]
I just did a git pull and will re-run it and let you know how it goes

**Comment by apperrault** [comment]
that worked.  thanks
