### ISSUE TITLE
Phantom "Server" Parameter Exception/Error

### ISSUE THREAD

**Issue by liamcs98** [sense-of-security/ADRecon#6]
I randomly keep getting this error when running the program.

Command
`C:\Users\<nope>\Desktop\AD-Recon-Logs\ADRecon.ps1 -DomainController <FQDN> -Credential domain\user -OutputDir C:\Users\<Nope>\Desktop\AD-Recon-Logs\Test\`

Error
`[*] ADRecon v180429 by Prashant Mahajan (@prashant3535) from Sense of Security.
[*] Running on <Domain>\Computer - Member Workstation
[EXCEPTION] A parameter cannot be found that matches parameter name 'Server'.`

**Comment by prashant3535** [comment]
You are already running from a host which is a member of a domain. Are you trying to run ADRecon against the same domain or another domain and which Protocol are using RSAT or LDAP?

**Comment by liamcs98** [comment]
Yep I'm just silly. Simply needed to do `-Protocol LDAP` and it started to work.
