### ISSUE TITLE
[ISSUE] Script generate following errors

### ISSUE THREAD

**Issue by MrZoltan** [sense-of-security/ADRecon#8]
Hi,

Would you have any idea why the following errors occurs ?
I am not proficient in Powershell unfortunately. 

"
At D:\powershell\activedirectory\ADRecon.ps1:121 char:86
+ ... "Header header-logged-out  position-relative f4 py-3" role="banner" >
+                                                                          ~
Missing file specification after redirection operator.
At D:\powershell\activedirectory\ADRecon.ps1:136 char:21
+ </a>                </li>
+                     ~
The '<' operator is reserved for future use.
At D:\powershell\activedirectory\ADRecon.ps1:140 char:21
+ </a>                </li>
+                     ~
The '<' operator is reserved for future use.
At D:\powershell\activedirectory\ADRecon.ps1:145 char:21
+ </a>                </li>
+                     ~
The '<' operator is reserved for future use.
At D:\powershell\activedirectory\ADRecon.ps1:150 char:21
+ </a>                </li>
+                     ~
The '<' operator is reserved for future use.
At D:\powershell\activedirectory\ADRecon.ps1:154 char:21
+ </a>                </li>
+                     ~
The '<' operator is reserved for future use.
At D:\powershell\activedirectory\ADRecon.ps1:388 char:185
+ ... TF-8" method="post"><input name="utf8" type="hidden" value="&#x2713;" ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.
At D:\powershell\activedirectory\ADRecon.ps1:392 char:18
+ </form>          <h3 class="pt-2">Join GitHub today</h3>
+                  ~
The '<' operator is reserved for future use.
At D:\powershell\activedirectory\ADRecon.ps1:501 char:53
+   <summary class="btn-link" aria-haspopup="dialog" >
+                                                     ~
Missing file specification after redirection operator.
At D:\powershell\activedirectory\ADRecon.ps1:518 char:17
+ </a>            </li>
+                 ~
The '<' operator is reserved for future use.
Not all parse errors were reported.  Correct the reported errors and try again.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : MissingFileSpecification
"
I have tried with many set of parameters without any change in errors

Thanks

Zoltan

**Comment by prashant3535** [comment]
Hi,
How have you downloaded the script? Could you please try doing a git clone or download the master zip from [https://github.com/sense-of-security/ADRecon/archive/master.zip](https://github.com/sense-of-security/ADRecon/archive/master.zip) ?

**Comment by MrZoltan** [comment]
Thanks Prashant,

That did the Job
I downloaded the script file directly form this website I suppose it was corrupted in the operation.

This script is really an awesome piece of work!

**Comment by prashant3535** [comment]
Thanks, appreciate the feedback.
