### ISSUE TITLE
Export to JSON gives XML output.

### ISSUE THREAD

**Issue by coaksford** [sense-of-security/ADRecon#9]
Choosing options to export to JSON gives XML output.

The JSON object is a string which does not have a .Save() method, it looks like this line was copied from the XML option where the XML object does have a .Save() method, so I just copied this from the HTML function and it works correctly.

Replace line 4159 in Function Export-ADRJSON, originally:

> (ConvertTo-JSON -InputObject $ADRObj).Save($ADFileName)

with:

> ConvertTo-JSON -InputObject $ADRObj | Out-File -FilePath $ADFileName

This looks like it was just an oversight while copying and pasting the XML function, but the Export-ADRJSON function was actually never called from anywhere in the script.

Replace line 4316 in Function Export-ADR, originally:

> Export-ADRXML -ADRObj $ADRObj -ADFileName $ADFileName

with:

> Export-ADRJSON -ADRObj $ADRObj -ADFileName $ADFileName

**Comment by prashant3535** [comment]
Thanks. Have pushed the fix.
